### ISSUE TITLE
Doesn't build on OSX (10.11.5)

### ISSUE THREAD

**Issue by jasonzoladz** [phonohawk/HsOpenSSL#58]
I have `openssl` installed and working.  But I get this error when building `HsOpenSSL`:

```bash
Configuring HsOpenSSL-0.11.1.1...
    Building HsOpenSSL-0.11.1.1...
    Preprocessing library HsOpenSSL-0.11.1.1...
    In file included from BN.hsc:45:
    /private/var/folders/7g/hqr575c56f57x2z04zkrfvm40000gn/T/stack18674/HsOpenSSL-0.11.1.1/cbits/HsOpenSSL.h:3:10: fatal error: 'openssl/asn1.h' file not found
    #include <openssl/asn1.h>
             ^
    1 error generated.
```

**Comment by jasonzoladz** [comment]
Duplicate issue of #41
